from utils.feature_extractor_contextualized import BertExtractor
from utils.feature_extractor_static import StaticEmbeddingExtractor
from utils.data_loader import SimplePhraseStaticDataset, PhraseAndContextDatasetBert, PhraseAndContextDatasetStatic, \
    StaticRankingDataset, SimplePhraseContextualizedDataset, SimplePhraseDataset, ContextualizedRankingDataset
